# Generated by Django 3.0.3 on 2020-11-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workably', '0003_auto_20201126_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='path',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
