# Generated by Django 3.0.3 on 2020-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workably', '0006_auto_20201126_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
