# Generated by Django 3.0.3 on 2020-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workably', '0007_auto_20201126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='plan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
