# Generated by Django 3.0.3 on 2020-11-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workably', '0008_auto_20201126_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='amount',
        ),
        migrations.AddField(
            model_name='impact',
            name='forecast_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='impact',
            name='plan_amount',
            field=models.IntegerField(null=True),
        ),
    ]
