# Generated by Django 3.2 on 2021-10-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workably', '0010_auto_20201130_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='workably.stream'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='workably.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
